name: Go

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Get dependencies
      run: go mod download

    - name: Build 
      run: go build -v .
      
    - name: Test
      run: go test -json -coverprofile=coverage.out ./...
    
    - name: Convert to coverage.xml
      run: |
        go get github.com/axw/gocov/gocov
        go get github.com/AlekSi/gocov-xml
        go install github.com/axw/gocov/gocov
        go install github.com/AlekSi/gocov-xml
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        gocov convert coverage.out | gocov-xml > coverage.xml
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        name: codecov-umbrella
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }} 
        # Path to coverage file to upload
        file: ./coverage.xml
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unittests
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: true
    
    - name: codacy-analysis-cli
      uses: mrfyda/codacy-analysis-cli-action@v1.0
      with:
        # 
        project-token: ${{ secrets.CODECY_TOKEN }} 

